// Generated by scripts/generate-keypair.ts on 2026-04-17T20:51:58.887Z.
// DO NOT EDIT by hand. To rotate, rerun `pnpm generate-keypair` and
// redeploy both the Worker (wrangler secret put) and the task-pane bundle.
export const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAFpHKyX2F/0hw1vjymeE5UWakkMSRH+E4+SjNuU15pSs=
-----END PUBLIC KEY-----`;
