/**
 * Legal writing vocabulary that standard English dictionaries don't include.
 * These are added to the spell-checker's "known words" set — flagging any of
 * them as misspelled would be false positives for legal writing.
 *
 * Curated list. Amend over time as new terms surface in testing.
 */
export const LEGAL_TERMS: readonly string[] = [
  // Latin legal phrases
  "habeas",
  "corpus",
  "mens",
  "rea",
  "prima",
  "facie",
  "res",
  "judicata",
  "ipso",
  "facto",
  "subpoena",
  "voir",
  "dire",
  "ad",
  "litem",
  "pro",
  "bono",
  "inter",
  "alia",
  "per",
  "curiam",
  "sub",
  "silentio",
  "pro",
  "rata",
  "de",
  "novo",
  "quid",
  "quo",
  "sine",
  "qua",
  "non",

  // Common legal abbreviations (whole-word only — reference formats handled elsewhere)
  "seq",
  "al",
  "et",
  "viz",
  "cf",

  // Legal-specific nouns
  "indemnitor",
  "indemnitee",
  "tortfeasor",
  "obligor",
  "obligee",
  "mortgagor",
  "mortgagee",
  "lessor",
  "lessee",
  "licensor",
  "licensee",
  "grantor",
  "grantee",
  "trustor",
  "trustee",
  "testator",
  "testatrix",
  "devisor",
  "devisee",
  "bailor",
  "bailee",
  "assignor",
  "assignee",
  "pledgor",
  "pledgee",

  // Common party types and legal roles
  "plaintiff",
  "defendant",
  "appellant",
  "appellee",
  "petitioner",
  "respondent",
  "amicus",
  "amici",
  "curiae",

  // Legal concepts and doctrines
  "estoppel",
  "laches",
  "novation",
  "subrogation",
  "severability",
  "indemnification",
  "hereunder",
  "thereunder",
  "whereunder",
  "herein",
  "therein",
  "wherein",
  "hereof",
  "thereof",
  "whereof",
  "hereto",
  "thereto",
  "whereto",
  "heretofore",
  "hereinafter",
  "aforementioned",
  "aforesaid",
  "notwithstanding",

  // Contract/agreement-specific
  "whereas",
  "therefor",
  "therefrom",
  "therewith",
  "whereunto",
  "severable",
  "waivable",
  "assignable",
  "nonassignable",
  "enforceable",
  "unenforceable",
  "nontransferable",

  // Court and procedure
  "banc",
  "interlocutory",
  "mandamus",
  "certiorari",
  "adjudicatory",
  "dispositive",
  "nondispositive",

  // Document types / structure
  "recitals",
  "counterclaim",
  "crossclaim",
  "impleader",
  "joinder",
  "interpleader",

  // Discovery
  "interrogatories",
  "interrogatory",
  "deposition",
  "deponent",
];
