#!/usr/bin/env tsx
/**
 * One-shot ed25519 keypair generator for the Fair Copy licensing system.
 *
 * Usage: `pnpm generate-keypair`
 *
 * Side effects:
 *  - Writes `.private-key.pem` to the fair-copy/ root (gitignored).
 *    Matt moves this into 1Password and runs
 *      `cd worker && wrangler secret put ED25519_PRIVATE_KEY < ../.private-key.pem`
 *    then deletes the local file.
 *  - Writes `src/licensing/public-key.ts` — a TypeScript constant module the
 *    task-pane bundle imports for offline JWT verification. THIS FILE IS
 *    COMMITTED. Rotating the keypair requires rerunning this script and
 *    redeploying the bundle.
 */
import { generateKeyPair, exportPKCS8, exportSPKI } from "jose";
import { writeFileSync } from "node:fs";

const { privateKey, publicKey } = await generateKeyPair("EdDSA", {
  crv: "Ed25519",
  extractable: true,
});
const privatePem = await exportPKCS8(privateKey);
const publicPem = await exportSPKI(publicKey);

writeFileSync("./.private-key.pem", privatePem);

const tsSource = `// Generated by scripts/generate-keypair.ts on ${new Date().toISOString()}.
// DO NOT EDIT by hand. To rotate, rerun \`pnpm generate-keypair\` and
// redeploy both the Worker (wrangler secret put) and the task-pane bundle.
export const PUBLIC_KEY_PEM = \`${publicPem.trim()}\`;
`;
writeFileSync("./src/licensing/public-key.ts", tsSource);

console.log("\u2713 Private key written to ./.private-key.pem");
console.log("  \u2192 Move it into your password manager");
console.log(
  "  \u2192 Then: cd worker && wrangler secret put ED25519_PRIVATE_KEY < ../.private-key.pem",
);
console.log("  \u2192 Then: rm ./.private-key.pem");
console.log("\u2713 Public key baked into ./src/licensing/public-key.ts (commit this file).");
